### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by timrourke**
This PR improves the README for Footprints to include more detailed setup instructions.

@paytonrules @cmvandrevala please review.

### CODE REVIEW

**Comment by timrourke** [comment]
@ryanzverner @cmvandrevala It looks like there is another PR still pending merge that contains updates to the README. I will leave this PR open. Please notify me when https://github.com/8thlight/footprints-public/pull/13 is merged, as I believe there are additional improvements to be made here.

Thanks!

**Comment by paytonrules** [comment]
@timrourke - You need to make a fork of this repo - not put a PR on this one.

**Comment by ryanzverner** [comment]
@timrourke See Eric's comment, but also, now this repo has been updated with some recent changes.

**Comment by timrourke** [comment]
@paytonrules I was not aware that we are not to make PRs against the upstream repository. I have a fork, as you can see from this PR.

@ryanzverner I am aware that this PR would result in merge conflicts, which is why I sought your input.

I will close this PR. I would ask that you provide additional clarity about what we should be doing with the footprints repository going forward. Others may make the same mistake.

**Pull request closed without merging**
