### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by timrourke**
@bartboy011 please review.

Looks like we do not all share write permissions to master.

### CODE REVIEW

**Comment by timrourke** [comment]
@bartboy011 FYI

**Review by bartboy011 — APPROVED** [review]
Looks good!

**Comment by bartboy011** [comment]
Actually, looks like this PR is targeting `8thlight:master` instead of `mongeeses:master`, can you change that?

**Comment by timrourke** [comment]
dangit wrong base

**Pull request closed without merging**
